
[[deqp]]
deqp = "/deqp/modules/gles31/deqp-gles31"
caselists = ["/deqp/mustpass/gles31-master.txt"]
skips = ["install/deqp-llvmpipe-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-gl-config-name=rgba8888d24s8ms0", "--deqp-visibility=hidden"
]
fraction = 10
# Would be nice to just set the LD_PRELOAD here instead of in the job, so deqp-runner
# wasn't asanned, but then the renderer check in deqp-runner.sh fails to pull in asan.
# Long term I want to just move the renderer check to deqp-runner anyway.
#  [deqp.env]
#  LD_PRELOAD = "libasan.so.6"
