/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ALIGNOF_DOUBLE 8

#define ALIGNOF_VOID_P 8

#define CONFIGDIR "./fonts"

#define EXEEXT .exe

#define FC_CACHEDIR getenv("TEMP")

#define FC_DEFAULT_FONTS "fonts"

#define FC_FONTPATH ""

/* The type of gperf "len" parameter */
#define FC_GPERF_SIZE_T size_t

#define HAVE_STRUCT_DIRENT_D_TYPE 1
#undef __STDC__

#define FLEXIBLE_ARRAY_MEMBER /**/

#define FONTCONFIG_PATH "fonts"

#undef FREETYPE_PCF_LONG_FAMILY_NAMES

#define GETTEXT_PACKAGE "fontconfig"

#define HAVE_FCNTL_H 1

#define HAVE_FT_DONE_MM_VAR 1

#define HAVE_FT_GET_BDF_PROPERTY 1

#define HAVE_FT_GET_PS_FONT_INFO 1

#define HAVE_FT_GET_X11_FONT_FORMAT 1

#define HAVE_FT_HAS_PS_GLYPH_NAMES 1

#define HAVE_GETPID 1

#define HAVE_INTTYPES_H 1

#define HAVE_RAND 1

#define HAVE_STDINT_H 1

#define HAVE_STDIO_H 1

#define HAVE_STDLIB_H 1

#define HAVE_STRERROR 1

#define HAVE_STRING_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_TIME_H 1

#define HAVE_WCHAR_H 1

#define HAVE__MKTEMP_S 1

#define PACKAGE_BUGREPORT "https://gitlab.freedesktop.org/fontconfig/fontconfig/issues/new"

#define PACKAGE_NAME "fontconfig"

#define PACKAGE_STRING "fontconfig 2.17.1"

#define PACKAGE_TARNAME "fontconfig"

#define PACKAGE_URL ""

#define PACKAGE_VERSION "2.17.1"

#ifdef _WIN64
#define SIZEOF_VOID_P 8
#else
#define SIZEOF_VOID_P 4
#endif

#define USE_ICONV 0

#define WORDS_BIGENDIAN 0

#define inline __inline

#define ENABLE_LIBXML2

#define HAVE_FT_GET_NEXT_CHAR 1

#ifndef PATH_MAX
#define PATH_MAX 1024
#endif

#define HAVE_UNISTD_H 1
